
# These categories will be applied to all DAGs in the repo.
categories:
  - Data Quality
# List of DAGs that should be published to the Astronomer Registry.
dags:
  - path: dags/gx_tutorial.py
  - path: dags/gx_pandas.py